name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Build project
        run: |
          echo "Compilation du programme!!"
          mkdir build
          cd build
          cmake ..
          make
          mv main ../main
          mv test1 ../test1
          mv test2 ../test2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            main
            test1
            test2

  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Run Test 1
        run: |
          echo "Execution des tests 1"
          chmod +x test1
          ./test1

  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Run Test 2
        run: |
          echo "Execution des tests 2"
          chmod +x test2
          ./test2

  deploy:
    needs: [test1, test2]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Deploy binary
        run: |
          pwd
          id
          cp main /tmp/mainAppli
